import javax.swing.*;
import java.awt.*;

public class Demo1 extends JFrame {
    public static void main(String[] args) {
        JFrame JF = new JFrame("创建一个窗体");
        JF.setVisible(true);
               JF.setLocation(200, 200);

        Container container = new JFrame().getContentPane();

        container.setBackground(Color.WHITE);
        JLabel L = new JLabel("这是个窗口标签");
        container.add(L);
        JF.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
